version: "3"
services:
  nginx:
    image: nginx:1.20.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend
    restart: unless-stopped

  teampass:
    image: teampass/teampass
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: teampass.local
      VIRTUAL_PORT: 80
      CERT_NAME: YOUR_CERTIFICATE
    volumes:
      - ./:/var/www/html
    networks:
      - teampass-internal
      - backend
  db:
    restart: unless-stopped
    image: mariadb:10.5
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass
    volumes:
      - ./teampass-db:/var/lib/mysql
    networks:
      - teampass-internal

networks:
  frontend:
  backend:
  #  external: true
  teampass-internal:
